export interface BulkImportProgressEvent {
  type: 'progress' | 'complete' | 'error';
  done?: number;
  total?: number;
  currentFile?: string;
  summary?: {
    total: number;
    successful: number;
    failed: number;
    errors: { url: string; error: string }[];
  };
  message?: string;
}

export interface ComprehensiveCandidateData {
  id?: string;
  _id?: string;
  name: string;
  email: string;
  phone?: string;
  dateOfBirth?: string;
  gender?: string;
  maritalStatus?: string;
  currentRole: string;
  desiredRole?: string;
  currentCompany?: string;
  location: string;
  preferredLocation?: string;
  totalExperience: string;
  currentSalary?: string;
  expectedSalary?: string;
  noticePeriod?: string;
  highestQualification?: string;
  degree?: string;
  specialization?: string;
  university?: string;
  educationYear?: string;
  educationPercentage?: string;
  additionalQualifications?: string;
  technicalSkills?: string[];
  softSkills?: string[];
  languagesKnown?: string[];
  certifications?: string[];
  previousCompanies?: string[];
  jobTitles?: string[];
  workDuration?: string[];
  keyAchievements?: string[];
  workExperience?: any[];
  education?: any[];
  projects?: string[];
  awards?: string[];
  publications?: string[];
  references?: string[];
  linkedinProfile?: string;
  portfolioUrl?: string;
  githubProfile?: string;
  summary?: string;
  resumeText?: string;
  fileName?: string;
  filePath?: string;
  fileUrl?: string;
  fileHash?: string;
  status?: 'new' | 'reviewed' | 'shortlisted' | 'rejected' | 'hired' | 'interviewed' | 'selected' | 'on-hold';
  tags?: string[];
  rating?: number;
  notes?: string;
  uploadedAt?: string;
  updatedAt?: string;
  lastContacted?: string;
  interviewStatus?: 'not-scheduled' | 'scheduled' | 'completed' | 'offered' | 'accepted' | 'declined' | 'no-show' | 'rescheduled' | null;
  feedback?: string;
  uploadedBy?: string;
  embedding?: number[] | string;
  parsing_method?: string;
  parsing_confidence?: number;
  parsing_errors?: any[];
}
